### PR TITLE
Add support for Themes

### PR DESCRIPTION
**Pull request by injeniero**
While working with it, I found the color scheme you used was making it really hard to read long messages because they would have the same color for the Timestamp and AttrValue. So I thought it would be great to make it configurable.

Other changes in this PR:
- Use HandlerOptions in encoder to avoid repeating code.
- HandlerOptions should not be a pointer as it can't be modified from the outside. This is the same implementation as in slog.Handler.
- Encoder doesn't have internal state, so no need to be a pointer.
- Default Theme tries to follow as close as possible Zerolog's Console theme.
- Do not print empty Attr as described in Handler.Handle: This is described in Handler.Handle method: If an Attr's key and value are both the zero value, ignore the Attr.

### CODE REVIEW

**Comment by injeniero** [comment]
@phsym do you have an ETA for when you can review this?

**Comment by phsym** [comment]
Hi @injeniero I reviewed it already and it looks good to me. I just want to give it a try before merging. Give me a few days as I'm a bit busy on other stuff

**Review by phsym — APPROVED** [review]

**Comment by phsym** [comment]
@injeniero Thanks a lot. Works like a charm

**Comment by phsym** [comment]
Released in [v0.3.0](https://github.com/phsym/console-slog/releases/tag/v0.3.0)

**Pull request merged**
